IMS/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('dashboard/', include('dashboard.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('',views.dashboard_index, name='dashboard_index'),
    path('add-products/', views.add_products, name='add_products'),
    path('search-products/', views.search_available_products, name='search_available_products'),
    path('view-available-products/', views.view_available_products, name='view_available_products'),
    path('sell-available-products/', views.sell_available_products, name='sell_available_products'),
    path('view-sold-products/', views.view_sold_products, name='view_sold_products'),
    path('users/', views.users, name='users'),
]

dashboard/models.py
from datetime import datetime
from django.db import models

# Create your models here.

class Available_product_table(models.Model):
    product_name = models.CharField(max_length=50)
    product_price = models.IntegerField()
    product_quantity = models.IntegerField()

    def __str__(self):
        return f"{self.id} - {self.product_name} - {self.product_price} - {self.product_quantity}"


class Sold_product_table(models.Model):
    date_time = models.DateTimeField(auto_now=True)
    product_id = models.IntegerField()
    product_name = models.CharField(max_length=50)
    product_price = models.IntegerField()
    product_quantity = models.IntegerField()

    def __str__(self):
        return f"{self.id} - {self.date_time} - {self.product_id} - {self.product_name} - {self.product_price} - {self.product_quantity}"

dashboard/forms.py
from django import forms
from .models import Available_product_table

class AddProductForm(forms.ModelForm):
    product_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Product Name'}))
    product_price = forms.IntegerField(widget=forms.NumberInput(attrs={'class':'form-control','placeholder':'Enter Product Price'}))
    product_quantity = forms.IntegerField(widget=forms.NumberInput(attrs={'class':'form-control','placeholder':'Enter Quantity'}))

    class Meta():
        model = Available_product_table
        fields = '__all__'


class SearchForm(forms.Form):
    search_product = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Enter Product Name','class':'form-control my-0 py-1'}))

IMS/views.py
from django.shortcuts import render, HttpResponse


# Create your views here.

def index(request):
    return render(request,'index.html',context={'title':'Inventory Management System'})

dashboard/views.py
from django.shortcuts import render, HttpResponse, redirect
from . import models
from .forms import AddProductForm, SearchForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

@login_required
def dashboard_index(request):
    return render(request,'dashboard/index.html',context={'title':'Dashboard'})




    
#add_products
@login_required
def add_products(request):
    form = AddProductForm()

    if request.method == 'POST':
        form = AddProductForm(request.POST)
        
        if form.is_valid():
            form.save()
            
            context = {
                'result' : 'New Product Added successfully',
                'title':'Add Products',
            }
            return render(request,'dashboard/result.html',context=context)

        else:
            context = {
                'result' : 'ERROR',
                'title':'Add Products',
            }
            return render(request,'dashboard/result.html',context=context)

    context = {
        'form' : form,
        'title':'Add Products',
        }

    return render(request,'dashboard/add_product.html',context=context)





# search_available_products
@login_required
def search_available_products(request):
    form = SearchForm()

    if request.method == 'POST':
        form = SearchForm(request.POST)
        
        if form.is_valid():
            search_product = form.cleaned_data['search_product']
            
            all_products = models.Available_product_table.objects.filter(product_name = search_product).values()  
            #print(all_products)
            context = {
                'all_products' : all_products,
                'title' : 'Search Result',
            }
            
            return render(request,'dashboard/view_available_products.html',context=context)


    context = {
        'form' : form,
        'title':'Search Products',
        }

    return render(request,'dashboard/search_product.html',context=context)






# view_available_products 
@login_required
def view_available_products(request):

    all_products = models.Available_product_table.objects.all()
    context = {
        'all_products' : all_products,
        'title' : 'All Products',
        }
            
    return render(request,'dashboard/view_available_products.html',context=context)





# sell_available_products
@login_required
def sell_available_products(request):

    if request.method == 'POST':
        sell_product_id = request.POST['product_id']
        sell_qty = int(request.POST['sellqty'])
        
        sell_product = models.Available_product_table.objects.filter(id = sell_product_id).values()
        sell_product = sell_product[0]

        if  sell_qty <= sell_product['product_quantity']:
            product = models.Sold_product_table(
                product_id = sell_product['id'], 
                product_name = sell_product['product_name'],
                product_price = sell_product['product_price'],
                product_quantity = sell_qty,
            )
            product.save()

            # UPDATE Available_product_table
            remaning_qty = sell_product['product_quantity'] - sell_qty

            update_product = models.Available_product_table.objects.get(id = sell_product_id)
            update_product.product_quantity = remaning_qty
            update_product.save()
            
            context = {
                'result' : 'Product sold successfully!',
                'title':'Sell Products',
            }
            return render(request,'dashboard/result.html',context=context)

        else:
            context = {
                'result' : 'Enter Quantity is less than available stock or Product is Out of Stock!',
                'title':'Sell Products',
            }
            return render(request,'dashboard/result.html',context=context)
        

    all_products = models.Available_product_table.objects.all()
    context = {
        'all_products' : all_products,
        'title' : 'Sell Products',
        }
            
    return render(request,'dashboard/sell_products.html',context=context)






# view_sold_products
@login_required
def view_sold_products(request):
    all_sold_products = models.Sold_product_table.objects.all()
    context = {
        'all_sold_products' : all_sold_products,
        'title' : 'Sold Products',
        }
            
    return render(request,'dashboard/view_sold_products.html',context=context)






@login_required
def users(request):
    form = UserCreationForm

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        
        if form.is_valid():
            form.save()
            
            context = {
                'result' : 'User Added successfully',
                'title':'Add User',
            }
            return render(request,'dashboard/result.html',context=context)

        else:
            context = {
                'result' : 'ERROR - Does not meet the requirements!',
                'title':'Add User',
            }
            return render(request,'dashboard/result.html',context=context)

    context = {
        'form' : form,
        'title':'Add User',
        }

    return render(request,'dashboard/user.html',context=context)

dashboard/templates/dashboard/add_product.html
{% extends 'dashboard/base.html' %}
{% block dashboardcontent %}

    <form method="POST">
        {% csrf_token %}

        <div class="form-group mx-4 mt-4">
            {{form.as_p}} 
        </div>
        
        <div class="form-group mx-4 mt-4">
            <button type="submit" class="btn login-btn btn-block ">Add Product</button>
        </div>
    </form>

        
{% endblock %}

dashboard/templates/dashboard/base.html
{% extends 'base.html' %}
{% block content %}

    <div class="container h-100">
        <div class="row align-items-center h-100" >
            
            <div class="col-9 mx-auto">

                <div class="mt-4">
                    <div class="text-center p-1">
                        <h3 class="theme-color">{{title}}</h3>
                    </div>
                </div>

                {% block dashboardcontent %}

                {% endblock %}

            </div>
        </div>
    </div>


{% endblock %}

dashboard/templates/dashboard/index.html
{% extends 'base.html' %}
{% block content %}

  <div class="mt-4">
    <div class="text-center p-3">
        <h2 class="theme-color">Dashboard</h2>
    </div>
  </div>

  <div class="container">
    <div class="row my-4">

      <div class="col-sm">
        <button class="btn btn-block action-btn p-3" onclick="location.href='{% url 'dashboard:add_products' %}'">
          <i class="far fa-plus-square pr-3"></i> Add Products
        </button>
      </div>

      <div class="col-sm">
        <button class="btn btn-block action-btn p-3" onclick="location.href='{% url 'dashboard:search_available_products' %}'">
          <i class="fas fa-search pr-3"></i> Search Products
        </button>
      </div>

      <div class="col-sm">
        <button class="btn btn-block action-btn p-3" onclick="location.href='{% url 'dashboard:view_available_products' %}'">
          <i class="fas fa-boxes pr-3"></i> View Available Products
        </button>
      </div>

    </div>

    <div class="row my-4">
      <div class="col-sm">
        <button class="btn btn-block action-btn p-3" onclick="location.href='{% url 'dashboard:sell_available_products' %}'">
          <i class="far fa-minus-square pr-3"></i> Sell Products
        </button>
      </div>

      <div class="col-sm">
        <button class="btn btn-block action-btn p-3" onclick="location.href='{% url 'dashboard:view_sold_products' %}'">
          <i class="fas fa-boxes pr-3"></i> View Sold Products
        </button>
      </div>

      <div class="col-sm">
        <button class="btn btn-block action-btn p-3" onclick="location.href='{% url 'dashboard:users' %}'">
          <i class="fas fa-user-shield pr-3"></i> Users
        </button>
      </div>

    </div>
  </div>
      

{% endblock  %}

dashboard/templates/dashboard/result.html
{% extends 'dashboard/base.html' %}
{% block dashboardcontent %}

<h3 class='text-center m-4'>{{result}}</h3>

<button class='btn action-btn btn-block' onclick="location.href={% url 'dashboard:dashboard_index' %}">Go Back</button>
        
{% endblock %}

dashboard/templates/dashboard/search_product.html
{% extends 'dashboard/base.html' %}
{% block dashboardcontent %}

    <form method="POST">
        <div class="input-group md-form form-md form-2 p-3">
            {{form.search_product}}
            {% csrf_token %}
           
            <button class="btn my-0 py-1" type="submit">
                <span class="input-group-text search-btn" id="basic-text1">
                    <i class="fas fa-search fa-fw search-icon" aria-hidden="true"></i>
                </span>
            </button>
        
        </div>
    </form>

{% endblock %}

dashboard/templates/dashboard/sell_products.html
{% extends 'dashboard/base.html' %}
{% block dashboardcontent %}

    <form method="POST">
        {% csrf_token %}
        <div class="form-group mx-4 mt-4">
            <select name='product_id' class="form-control" required>
                <option value="" disabled selected hidden>-- Select Product --</option>
                {% if all_products.count > 0 %}

                    {% for item in all_products %}
                        <option value={{item.id}}>Product id: {{item.id}}  - {{item.product_name}}</option>
                    {% endfor %}

                {% endif %}
            </select>
        </div>
        
        <div class="form-group mx-4 mt-4">
            <input type="number" required name="sellqty" class="form-control" placeholder="Quantity" min="1">
        </div>

        <div class="form-group mx-4 mt-4">
            <button type="submit" class="btn login-btn btn-block ">Sell Product</button>
        </div>
    </form>

{% endblock %}

dashboard/templates/dashboard/test.html
{% extends 'dashboard/base.html' %}
{% block dashboardcontent %}

TEST HTML DATA

{% endblock %}

dashboard/templates/dashboard/user.html
{% extends 'dashboard/base.html' %}
{% block dashboardcontent %}

    <form method="POST">
        {% csrf_token %}

        <div class="form-group mx-4 mt-4">
            {{form.username.label_tag}}
            <input type="text" required name="username" class="form-control" placeholder="Enter Username">
        </div>

        <div class="form-group mx-4 mt-4">
            {{form.password1.label_tag}}
            <input type="password" required  name="password1" class="form-control" placeholder="Enter Password">
        </div>

        <div class="form-group mx-4 mt-4">
            {{form.password2.label_tag}}
            <input type="password" required  name="password2" class="form-control" placeholder="Enter the same password as before, for verification.">
        </div>
        
        <div class="form-group mx-4 mt-4">
            <button type="submit" class="btn login-btn btn-block ">Add User</button>
        </div>
       
    </form>

{% endblock %}

dashboard/templates/dashboard/view_available_products.html
{% extends 'dashboard/base.html' %}
{% block dashboardcontent %}

    {% if all_products.count > 0 %}

        <table class='table table-striped'>
            <thead>
                <tr>
                    <th scope='col'>Product ID</th>
                    <th scope='col'>Product Name</th>
                    <th scope='col'>Product Price</th>
                    <th scope='col'>Quantity</th>
                </tr>
            </thead>
            
            <tbody>
                {% for item in all_products %}
                    <tr>
                        <td scope='row'>{{item.id}}</th>
                        <td scope='row'>{{item.product_name}}</td>
                        <td scope='row'>{{item.product_price}}</td>
                        <td scope='row'>{{item.product_quantity}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    
    {% else %}
        <h1 class='text-center'>No Products are thier to view....</h1>

    {% endif %}
    
    <button class='btn action-btn btn-block' onclick="location.href={% url 'dashboard:dashboard_index' %}">Go Back</button>          


{% endblock %}

dashboard/templates/dashboard/view_sold_products.html
{% extends 'dashboard/base.html' %}
{% block dashboardcontent %}

    {% if all_sold_products.count > 0 %}

        <table class='table table-striped'>
            <thead>
                <tr>
                    <th scope='col'>Date Time</th>
                    <th scope='col'>Product ID</th>
                    <th scope='col'>Product Name</th>
                    <th scope='col'>Product Price</th>
                    <th scope='col'>Quantity</th>
                </tr>
            </thead>
            
            <tbody>
                {% for item in all_sold_products %}
                    <tr>
                        <td scope='row'>{{item.date_time}}</th>
                        <td scope='row'>{{item.product_id}}</th>
                        <td scope='row'>{{item.product_name}}</td>
                        <td scope='row'>{{item.product_price}}</td>
                        <td scope='row'>{{item.product_quantity}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    
    {% else %}
        <h1 class='text-center'>No Products are thier to view....</h1>

    {% endif %}
    
    <button class='btn action-btn btn-block' onclick="location.href={% url 'dashboard:dashboard_index' %}">Go Back</button>          


{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}} - IMS</title>
    

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- 
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    
        <link rel="stylesheet" href="vender/css/all.css">
    -->
</head>

<body>
  
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
        
        {% if user.is_authenticated %}
            <a class="navbar-brand my-0 mr-md-auto" href="{% url 'dashboard:dashboard_index' %}">
                <img src="{% static 'img/logo.svg' %}" alt="logo" width="130" height="30" alt="Logo" loading="lazy">
            </a>
            <button class="btn btn-outline logout-btn" onclick="location.href='{% url 'logout' %}'">Logout ({{user.username | capfirst}})</button>

        {% else %}
            <a class="navbar-brand my-0 mr-md-auto" href="{% url 'index' %}">
                <img src="{% static 'img/logo.svg' %}" alt="logo" width="130" height="30" alt="Logo" loading="lazy">
            </a>
            <button class="btn btn-outline logout-btn" onclick="location.href='{% url 'login' %}'">Login</button>

        {% endif %}

    </div>



    {% block content %}

    {% endblock %}

        
</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="container h-100">
    <div class="row text-center align-items-center h-100 " >
        <div class="col-12 mx-auto">
            <div class="mt-4">
                <div class="text-center p-2">
                    <h1 class="theme-color">Inventory Management System</h1>
                    <h5></h5>
                </div>
            </div>
        </div>
        <div class="col-12 mx-auto">
            <div class="mt-4">
                <div class="text-center p-2">
                    <h3 class="theme-color">Developer</h3>
                </div>
            </div>
        </div>
  
       
        <!-- Team member-1 HERE -->
        <div class="col-lg-12 center team-menbers">
            <img src="{% static 'img/runal.png' %} " class="rounded-circle" width="120" height="120">
            <h6 class="m-1">Aditya Ghatge</h6>
            
        </div>
           
    </div>


</div>
      

{% endblock  %}